api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "bundle-discount"
type = "function"
uid = "208e9edf-8b9b-6b74-3f3a-539fdede2328f859a084"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"



  [extensions.build]
  command = ""
  path = "dist/function.wasm"
